import { type NextPage } from "next";
import Head from "next/head";
import { api } from "@/utils/api";

const Home: NextPage = (props) => {
  const {
    data: randomMovie,
    isLoading,
    isError,
  } = api.movie.getRandomMovie.useQuery();

  if (isLoading || !randomMovie) return <p>Loading ...</p>;

  if (isError) return <p>Error</p>;

  return (
    <>
      <Head>
        <title>Filmoji 🍿</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#DC2026] to-[#7E1616]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Start playing <span className="text-[#FCC252]">Filmoji 🍿</span>
          </h1>
          <div className="text-xl">Movie : {randomMovie.proposedEmoji}</div>
          <div className="flex w-3/5 flex-row justify-items-center gap-4 align-middle">
            <input
              placeholder="Hello"
              className="block  w-full rounded-lg border border-secondary-200 bg-transparent p-2.5 text-sm text-secondary-200 placeholder-secondary-400 focus:border-yellow-500 focus:ring-yellow-500"
            />
            <button className="rounded bg-primary-500 px-4 py-2 font-semibold text-gray-800 shadow hover:bg-primary-600">
              Guess
            </button>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
